template: |
  ## What's changed 
  $CHANGES
  
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"

change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
no-changes-template: "- No significant changes."

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "fix"
      - "chore"
